### ISSUE TITLE
Review for Assignment 2

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/ABC#115]
Hey Team,
I was about to start the review for assignment2.
Please share your Jenkins credentials with me on Slack.

**Comment by chetan253** [comment]
Hi @nawazkh,
I've emailed you the credentials. Kindly go through.
-Chetan

**Comment by nawazkh** [comment]
Hey Team, I am sorry I forgot to share my feedback, so here it goes.
There were few things missing at the time of grading of assignment 2, I have listed them below:
1. The services were being built on the same instance where they were being deployed. IMO, there should be one dev environment used to build a system and deploy it to production servers. Please do implement that.
2. We are also looking for functionality improvement, so if there was any functionality improved over as the part of sprints, do include it in your wiki.
 
However, I really like the project concept and the work put behind it. 
Keep up the good work!

**Comment by chetan253** [comment]
Hi @nawazkh,

Thanks, for your feedback. I would like you to know that the services were built and tested on Jenkins server while they were deployed on production server.  The reason we opted for this was due to less number of  instances available to create on IU jetstream. However, if you are referring to current implementation then we have made some changes based on Milestone 3.

Thanks,
Chetan
