### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/ABC#39]
1. Are the API's exposed on wiki authenticated before they'r processed?
Ex: DELETE : http://localhost:8080/tweet/deleteByTweetId/5c59282a2ad5c62ef6fc69e0

2. Why does the tweet post API return the tweet as response?
POST : http://localhost:8080/tweet/create/
also create user, POST : http://localhost:3000/user

Please see first two answers: https://stackoverflow.com/questions/1829875/is-it-ok-by-rest-to-return-content-after-post.

Please, add what is being achieved with the above in the comment.

3. Is TweetLike model just a relationship entity ? user and tweet? (many to many)
Can we not save Collection User {
 likes : [list of tweet ids]
}

SImilarly, User and followers or may be following list in user.

is there anything else achieved with the current design we have?

4. Is the request authenticated: 
DELETE : http://localhost:3000/user.
Who will be deleting an user? Is there a admin role?
Request Body:
{
    "userId": "c4836160-2914-11e9-8b00-99a430df561b"
}

Response Body:
{
    "deletedCount": 1
}

I don't think we can pass multiple userIds in request, then why we need count as response? . Is there a possibility that the user deleted by an admin doesn't exist in DB?- if not, the response will always have a count 1, else a response body will have an error status in case of any failures.

5. Does this work? GET method
GET http://localhost:3000/user/search

Request Body:
{
    "userId": "7e4fdd8c-f148-44fc-a187-283c0e142c41",
    "searchQuery": "doe"
}

6. Under /feed, What is the purpose of 
@RequestMapping(value = "/create/{userId}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)

creating user? using GET , under /feed ?

7. User management... Can we move the url handler code out of server JS and have respective mapped modules.

Please help us understand better.

**Comment by absheth** [comment]
Thank you for the detailed analysis.

Please find our responses below:

1) A user will only be able to delete the tweet once he is logged in. So in a sense, yes but deleting tweet functionality is unavailable. A user will just be able to create tweets and get tweets posted by other users in its feed.

Currently, all the APIs are exposed and I believe one of our future milestones is going to be service discovery which should handle this. So we do not plan on implementing that for the first milestone.

2)Thank you for pointing that out. We are sending tweet response back as the user who creates the tweet will get the tweet back in case if the tweet is created instead of making one another REST call just to get that tweet and show on their wall. 
Basically, our intention was to use listeners where once the tweet is created, it will be sent via sockets or notification to which the users, in turn, will be listening either using long polling or getting it through notification and populating the same on their own wall. Since the time was limited we didn’t target live updates in this milestone and hence sent the response back as a tweet.

3) Things become serious when the likes come in huge numbers. In near future, it will be heavy for service to retrieve likes for a particular post. You’ll need to iterate through all users (linear) and check if that user has liked the tweet or not (linear) with the model you proposed which becomes n^2 for database search unless you create an index which possibly makes log(n). Keeping likes to tweet mapping in a separate collection will take linear time for DB and also it will be easy to get if the user liked that post or not. Also, likes keep updating each second when there is a large user base, in such case creating indexes becomes costly every time hit is made on collection. Same applies to followers.

This will help clear your doubt :
https://stackoverflow.com/questions/12994594/how-should-i-store-likes-dislikes-and-rating-in-mongoose-mongdb-using-node-js

4) Our application does not support deleting users. That functionality was implemented to check whether the user is being created or not with the fake backend during the learning process.
If you required, we can get rid of code related to deleting a user from the code base but we would like to keep it for our future reference as it is one of the work codes.

5) The body cannot be passed in the GET method. We are using the ‘fetch’ javascript method and it gave us an error while sending the body in GET request.

6) We are not creating a user over there but /feed/create/{userId} is the endpoint where feed for that userID is generated.

7) Fixed.

**Comment by harishmaruthi** [comment]
It was a good learning for me. Thanks for time for that detailed response.
